version: '3'

services:
  mock:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn mock_openai_server:app --reload
    environment:
      - RESPONSE_MODE=echo
    network_mode: host

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python main.py
    environment:
      - OCP_OPENAI_API_KEY=test_api_key
      - OCP_OPENAI_ORG=test
      - OCP_OPENAI_API_BASE=http://localhost:8000/v1
    network_mode: host

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "poetry run pytest -x && exit 0 || exit 1"
    depends_on:
      - flask
      - mock
    environment:
      - FASTAPI_BASE_URL=http://localhost:8000/v1/completions
      - FLASK_BASE_URL=http://localhost:5000/v1/completions
    profiles:
      - test
    network_mode: host
