version: '3'

services:
  mock_server:
    build:
      context: .
      dockerfile: Containerfile
    command: uvicorn mock_openai_server:app --host 0.0.0.0 --reload
    ports:
      - '8000:8000'
    environment:
      - RESPONSE_MODE=echo

  flask_server:
    build:
      context: .
      dockerfile: Containerfile
    command: flask --app main:app --debug run --host 0.0.0.0
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=main:app
      - FLASK_ENV=development
      - OCP_OPENAI_API_KEY=your_openai_api_key_here
      - OCP_OPENAI_ORG=your_openai_org_here
      - OCP_OPENAI_API_BASE=your_openai_api_base_here

  test:
    build:
      context: .
      dockerfile: Containerfile
    command: /bin/sleep infinity  # Keeps the container running so we can exec into it to run tests
